workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 20
        YARN_VERSION: latest
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Build APK
        script: npx react-native run-android --variant=release
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
