workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 20
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.gradle/caches
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Give Gradlew Permission
        script: chmod +x android/gradlew
      - name: Clean Gradle Build
        script: cd android && ./gradlew clean
      - name: Build APK
        script: cd android && ./gradlew assembleRelease -Pandroid.disableResourceValidation=true
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
